

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated based on the Unicorn serialisation items
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable InconsistentNaming
namespace RainbowCodeGeneration.Test
{
	using global::Sitecore.Data;

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
    public struct SitecoreKnownItems
    {
	
        /// <summary>
		/// Maps
		/// <para></para>
		/// <para>Path: /sitecore/layout/Renderings/Feature/Maps</para>	
		/// <para>ID: 02eda08e-78e1-409c-9655-a2f43abe09f3</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Maps
        {
			/// <summary>
			/// The ID for /sitecore/layout/Renderings/Feature/Maps
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{02eda08e-78e1-409c-9655-a2f43abe09f3}");

			/// <summary>
			/// The TemplateId string for /sitecore/layout/Renderings/Feature/Maps
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "a87a00b1-e6db-45ab-8b54-636fec3b5523";        
            
            /// <summary>
		/// Map
		/// <para></para>
		/// <para>Path: /sitecore/layout/Renderings/Feature/Maps/Map</para>	
		/// <para>ID: 7dfd9396-cb94-4174-9721-9419a2aa68e3</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Map
        {
			/// <summary>
			/// The ID for /sitecore/layout/Renderings/Feature/Maps/Map
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{7dfd9396-cb94-4174-9721-9419a2aa68e3}");

			/// <summary>
			/// The TemplateId string for /sitecore/layout/Renderings/Feature/Maps/Map
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "99f8905d-4a87-4eb8-9f8b-a9bebfb3add6";        
            
            		}
    		}
    		
	}
}

