//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated based on the Unicorn serialisation items
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable InconsistentNaming
namespace RainbowCodeGeneration.Test
{
	using Sitecore.Data;

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
    public struct SitecoreTemplates
    {
	
		/// <summary>
		/// Map Type
		/// <para></para>
		/// <para>Path: /sitecore/templates/Feature/Maps/Map Type</para>	
		/// <para>ID: 04c34cf5-b7ea-4408-88e8-5fc851173dbd</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Map_Type
        {
			/// <summary>
			/// The ID for /sitecore/templates/Feature/Maps/Map Type
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{04c34cf5-b7ea-4408-88e8-5fc851173dbd}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Feature/Maps/Map Type
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "04c34cf5-b7ea-4408-88e8-5fc851173dbd";

			public struct Name
            {
				/// <summary>
				/// The Name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "Name";
            }
		}

		/// <summary>
		/// _MapPoint
		/// <para></para>
		/// <para>Path: /sitecore/templates/Feature/Maps/_MapPoint</para>	
		/// <para>ID: 1e6a8c8c-6646-4776-8ab4-615265669633</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct _MapPoint
        {
			/// <summary>
			/// The ID for /sitecore/templates/Feature/Maps/_MapPoint
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{1e6a8c8c-6646-4776-8ab4-615265669633}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Feature/Maps/_MapPoint
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "1e6a8c8c-6646-4776-8ab4-615265669633";

			public struct MapPointAddress
            {
				/// <summary>
				/// The MapPointAddress field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// </summary>
                public const string FieldName = "MapPointAddress";
            }

			public struct MapPointLocation
            {
				/// <summary>
				/// The MapPointLocation field.
				/// <para></para>
				/// <para>Field Type: Map Field</para>		
				/// </summary>
                public const string FieldName = "MapPointLocation";
            }

			public struct MapPointName
            {
				/// <summary>
				/// The MapPointName field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "MapPointName";
            }
		}

		/// <summary>
		/// _MapPoints Folder
		/// <para></para>
		/// <para>Path: /sitecore/templates/Feature/Maps/_MapPoints Folder</para>	
		/// <para>ID: 31713995-c6bf-4ccb-8807-198493508afa</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct _MapPoints_Folder
        {
			/// <summary>
			/// The ID for /sitecore/templates/Feature/Maps/_MapPoints Folder
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{31713995-c6bf-4ccb-8807-198493508afa}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Feature/Maps/_MapPoints Folder
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "31713995-c6bf-4ccb-8807-198493508afa";
		}

		/// <summary>
		/// _MapRenderingParameters
		/// <para></para>
		/// <para>Path: /sitecore/templates/Feature/Maps/_MapRenderingParameters</para>	
		/// <para>ID: d77856c3-8a5e-452c-8854-f2965edf25e0</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct _MapRenderingParameters
        {
			/// <summary>
			/// The ID for /sitecore/templates/Feature/Maps/_MapRenderingParameters
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{d77856c3-8a5e-452c-8854-f2965edf25e0}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Feature/Maps/_MapRenderingParameters
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "d77856c3-8a5e-452c-8854-f2965edf25e0";

			public struct CenterLocation
            {
				/// <summary>
				/// The CenterLocation field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "CenterLocation";
            }

			public struct EnableCenterMapControl
            {
				/// <summary>
				/// The EnableCenterMapControl field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "EnableCenterMapControl";
            }

			public struct EnableMapTypeControl
            {
				/// <summary>
				/// The EnableMapTypeControl field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "EnableMapTypeControl";
            }

			public struct EnableRotateControl
            {
				/// <summary>
				/// The EnableRotateControl field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "EnableRotateControl";
            }

			public struct EnableScaleControl
            {
				/// <summary>
				/// The EnableScaleControl field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "EnableScaleControl";
            }

			public struct EnableStreetViewControl
            {
				/// <summary>
				/// The EnableStreetViewControl field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "EnableStreetViewControl";
            }

			public struct EnableZoomControl
            {
				/// <summary>
				/// The EnableZoomControl field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "EnableZoomControl";
            }

			public struct MapType
            {
				/// <summary>
				/// The MapType field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// </summary>
                public const string FieldName = "MapType";
            }

			public struct ZoomLevel
            {
				/// <summary>
				/// The ZoomLevel field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "ZoomLevel";
            }
		}
	}
}